# Generated by Django 3.2.8 on 2022-02-08 09:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facade', '0003_reservation_equal reservation on this app by this user is already in place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installed_at', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('name', models.CharField(default='Nana', help_text='This waiters Name', max_length=2000)),
                ('identifier', models.CharField(default='main', max_length=1000)),
                ('unique', models.CharField(default=uuid.uuid4, help_text='The Channel we are listening to', max_length=1000)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONNECTED', 'Disconnected'), ('VANILLA', 'Complete Vanilla Scenario after a forced restart of')], default='VANILLA', help_text='The Status of this Waiter', max_length=1000)),
                ('registry', models.ForeignKey(help_text='The provide might be limited to a instance like ImageJ belonging to a specific person. Is nullable for backend users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='facade.registry')),
            ],
        ),
        migrations.AddConstraint(
            model_name='waiter',
            constraint=models.UniqueConstraint(fields=('registry', 'identifier'), name='No multiple Waiters for same App and User allowed on same identifier'),
        ),
    ]
